BEGIN;
DROP FUNCTION IF EXISTS public.sales_close_recovery_v1(text);
DROP FUNCTION IF EXISTS public.sales_close_preview_v2(uuid,date,date);
DROP FUNCTION IF EXISTS public.sales_close_period_v1(uuid,text);
DROP FUNCTION IF EXISTS public.sales_close_period_v2(uuid,text,date,date,text);
DROP FUNCTION IF EXISTS public.sales_close_preview_revision_v1(uuid,uuid);
DROP TRIGGER IF EXISTS sales_close_guard_celebrations ON public.sales_celebrations;
DROP TRIGGER IF EXISTS sales_close_guard_holidays ON public.sales_holidays;
DROP TRIGGER IF EXISTS sales_close_guard_assignments ON public.sales_goal_assignments;
DROP TRIGGER IF EXISTS sales_close_guard_config ON public.sales_config;
DROP TRIGGER IF EXISTS sales_close_guard_sales ON public.sales;
DROP FUNCTION IF EXISTS public.sales_close_material_write_guard_v1();
ALTER FUNCTION public.sales_close_period_legacy_10_1(uuid,text) RENAME TO sales_close_period_v1;
REVOKE EXECUTE ON FUNCTION public.sales_close_period_v1(uuid,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.sales_close_period_v1(uuid,text) TO authenticated;
DROP TABLE IF EXISTS public.sales_period_close_requests;
DROP TRIGGER IF EXISTS sales_period_closure_immutable_v1_trigger ON public.sales_period_closures;
DROP FUNCTION IF EXISTS public.sales_period_closure_immutable_v1();
ALTER TABLE public.sales_period_closures DROP CONSTRAINT IF EXISTS sales_period_closures_next_period_tenant_fk,DROP COLUMN IF EXISTS next_period_id,DROP COLUMN IF EXISTS result,DROP COLUMN IF EXISTS request;
COMMIT;
