BEGIN;

ALTER TABLE public.sales ADD COLUMN revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0);

CREATE TABLE public.sales_mutation_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) BETWEEN 1 AND 200),
  operation text NOT NULL CHECK (operation IN ('UPSERT','CANCEL')),
  request jsonb NOT NULL,
  result jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id,idempotency_key)
);
ALTER TABLE public.sales_mutation_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sales_mutation_requests FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.sales_admin_dashboard_v2(p_period_id uuid,p_consultant_profile_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE v_tenant uuid:=public.auth_tenant_id();v_metrics jsonb;v_pipeline jsonb;v_rank jsonb;v_installments jsonb;
BEGIN
 IF v_tenant IS NULL OR auth.uid() IS NULL OR NOT public.sales_is_admin() THEN RAISE EXCEPTION 'sales_admin_required' USING ERRCODE='42501';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.sales_periods sp WHERE sp.tenant_id=v_tenant AND sp.id=p_period_id) OR (p_consultant_profile_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.sales_memberships sm WHERE sm.tenant_id=v_tenant AND sm.profile_id=p_consultant_profile_id AND sm.role='CONSULTANT')) THEN RAISE EXCEPTION 'sales_not_found_or_out_of_scope' USING ERRCODE='P0002';END IF;
 v_metrics:=public.sales_metrics_internal_v1(v_tenant,p_period_id,p_consultant_profile_id,NULL);
 SELECT jsonb_build_object('value',COALESCE(sum(s.sale_value-s.discount_value),0),'sales_count',count(*),'pieces_total',COALESCE(sum(s.pieces_total),0),'freight_total',COALESCE(sum(s.freight_value),0)) INTO v_pipeline FROM public.sales s WHERE s.tenant_id=v_tenant AND s.period_id=p_period_id AND s.status='OPEN' AND (p_consultant_profile_id IS NULL OR s.consultant_profile_id=p_consultant_profile_id);
 SELECT COALESCE(jsonb_agg(jsonb_build_object('profile_id',x.profile_id,'display_name',x.full_name,'realized_value',x.realized,'sales_count',x.sales_count,'position',x.position) ORDER BY x.position,x.full_name,x.profile_id),'[]') INTO v_rank FROM(SELECT q.*,rank()OVER(ORDER BY q.realized DESC,q.sales_count DESC,q.full_name,q.profile_id)position FROM(SELECT p.id profile_id,p.full_name,COALESCE(sum(s.sale_value-s.discount_value)FILTER(WHERE s.status='CLOSED'),0)realized,count(s.id)FILTER(WHERE s.status='CLOSED')sales_count FROM public.sales_memberships sm JOIN public.profiles p ON p.tenant_id=sm.tenant_id AND p.id=sm.profile_id LEFT JOIN public.sales s ON s.tenant_id=sm.tenant_id AND s.consultant_profile_id=sm.profile_id AND s.period_id=p_period_id WHERE sm.tenant_id=v_tenant AND sm.role='CONSULTANT' AND sm.is_active GROUP BY p.id,p.full_name)q)x;
 SELECT jsonb_build_object('closed',COALESCE(jsonb_agg(jsonb_build_object('installments',x.installments,'sales_count',x.sales_count,'value',x.value)ORDER BY x.installments)FILTER(WHERE x.status='CLOSED'),'[]'),'open',COALESCE(jsonb_agg(jsonb_build_object('installments',x.installments,'sales_count',x.sales_count,'value',x.value)ORDER BY x.installments)FILTER(WHERE x.status='OPEN'),'[]')) INTO v_installments FROM(SELECT s.status,s.installments,count(*)sales_count,COALESCE(sum(s.sale_value-s.discount_value),0)value FROM public.sales s WHERE s.tenant_id=v_tenant AND s.period_id=p_period_id AND s.status IN('CLOSED','OPEN') AND(p_consultant_profile_id IS NULL OR s.consultant_profile_id=p_consultant_profile_id)GROUP BY s.status,s.installments)x;
 RETURN jsonb_build_object('period_id',p_period_id,'consultant_profile_id',p_consultant_profile_id,'realized',v_metrics,'pipeline',v_pipeline,'installments',v_installments,'tickets',jsonb_build_object('sale',CASE WHEN (v_metrics->>'sales_count')::numeric=0 THEN 0 ELSE round((v_metrics->>'realized_value')::numeric/(v_metrics->>'sales_count')::numeric,2)END,'piece',CASE WHEN (v_metrics->>'pieces_total')::numeric=0 THEN 0 ELSE round((v_metrics->>'realized_value')::numeric/(v_metrics->>'pieces_total')::numeric,2)END),'ranking',v_rank);
END;$$;

CREATE OR REPLACE FUNCTION public.sales_admin_list_sales_v1(p_period_id uuid DEFAULT NULL,p_consultant_profile_id uuid DEFAULT NULL,p_status public."SalesSaleStatus" DEFAULT NULL,p_page integer DEFAULT 1,p_page_size integer DEFAULT 25,p_sort text DEFAULT 'sold_at',p_direction text DEFAULT 'desc')
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE v_tenant uuid:=public.auth_tenant_id();v_total bigint;v_items jsonb;
BEGIN
 IF v_tenant IS NULL OR auth.uid() IS NULL OR NOT public.sales_is_admin() THEN RAISE EXCEPTION 'sales_admin_required' USING ERRCODE='42501';END IF;
 IF p_page<1 OR p_page_size NOT BETWEEN 1 AND 100 OR p_sort NOT IN('sold_at','pv_number','sale_value','status') OR lower(p_direction) NOT IN('asc','desc') THEN RAISE EXCEPTION 'sales_filter_validation' USING ERRCODE='22023';END IF;
 IF (p_period_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.sales_periods sp WHERE sp.tenant_id=v_tenant AND sp.id=p_period_id)) OR (p_consultant_profile_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.sales_memberships sm WHERE sm.tenant_id=v_tenant AND sm.profile_id=p_consultant_profile_id)) THEN RAISE EXCEPTION 'sales_not_found_or_out_of_scope' USING ERRCODE='P0002';END IF;
 SELECT count(*) INTO v_total FROM public.sales s WHERE s.tenant_id=v_tenant AND (p_period_id IS NULL OR s.period_id=p_period_id) AND (p_consultant_profile_id IS NULL OR s.consultant_profile_id=p_consultant_profile_id) AND (p_status IS NULL OR s.status=p_status);
 SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.ordinal),'[]') INTO v_items FROM(SELECT row_number()OVER()ordinal,s.id,s.pv_number,s.sale_value,s.freight_value,s.discount_value,s.payment_method_id,s.installments,s.sets_count,s.loose_pieces_count,s.pieces_total,s.invoice_number,s.status,s.sold_at,s.revision,s.consultant_profile_id,p.full_name consultant_name,s.period_id,sp.status period_status,sp.starts_on,sp.ends_on,s.cancelled_at,s.cancellation_reason,CASE WHEN sp.status='OPEN' AND s.status<>'CANCELLED' THEN true ELSE false END can_edit,CASE WHEN sp.status='OPEN' AND s.status<>'CANCELLED' THEN true ELSE false END can_cancel FROM public.sales s JOIN public.profiles p ON p.tenant_id=s.tenant_id AND p.id=s.consultant_profile_id JOIN public.sales_periods sp ON sp.tenant_id=s.tenant_id AND sp.id=s.period_id WHERE s.tenant_id=v_tenant AND (p_period_id IS NULL OR s.period_id=p_period_id) AND (p_consultant_profile_id IS NULL OR s.consultant_profile_id=p_consultant_profile_id) AND (p_status IS NULL OR s.status=p_status) ORDER BY CASE WHEN p_sort='sold_at' AND lower(p_direction)='asc' THEN s.sold_at END ASC,CASE WHEN p_sort='sold_at' AND lower(p_direction)='desc' THEN s.sold_at END DESC,CASE WHEN p_sort='pv_number' AND lower(p_direction)='asc' THEN s.pv_number END ASC,CASE WHEN p_sort='pv_number' AND lower(p_direction)='desc' THEN s.pv_number END DESC,CASE WHEN p_sort='sale_value' AND lower(p_direction)='asc' THEN s.sale_value END ASC,CASE WHEN p_sort='sale_value' AND lower(p_direction)='desc' THEN s.sale_value END DESC,CASE WHEN p_sort='status' AND lower(p_direction)='asc' THEN s.status END ASC,CASE WHEN p_sort='status' AND lower(p_direction)='desc' THEN s.status END DESC,s.id ASC LIMIT p_page_size OFFSET(p_page-1)*p_page_size)x;
 RETURN jsonb_build_object('items',v_items,'page',p_page,'page_size',p_page_size,'total',v_total,'sort',p_sort,'direction',lower(p_direction),'filters',jsonb_build_object('period_id',p_period_id,'consultant_profile_id',p_consultant_profile_id,'status',p_status));
END;$$;

CREATE OR REPLACE FUNCTION public.sales_admin_upsert_sale_v2(p_sale_id uuid,p_consultant_profile_id uuid,p_pv_number text,p_sale_value numeric,p_freight_value numeric,p_discount_value numeric,p_payment_method_id uuid,p_installments integer,p_sets_count integer,p_loose_pieces_count integer,p_invoice_number text,p_status public."SalesSaleStatus",p_sold_at timestamptz,p_expected_revision bigint,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE v_tenant uuid:=public.auth_tenant_id();v_actor uuid:=auth.uid();v_key text:=btrim(COALESCE(p_idempotency_key,''));v_request jsonb;v_old_req jsonb;v_result jsonb;v_before jsonb;v_after jsonb;v_period uuid;v_pps int;
BEGIN
 IF v_tenant IS NULL OR v_actor IS NULL OR NOT public.sales_is_admin() THEN RAISE EXCEPTION 'sales_admin_required' USING ERRCODE='42501';END IF;
 IF length(v_key)NOT BETWEEN 1 AND 200 OR length(btrim(COALESCE(p_pv_number,'')))=0 OR p_sale_value<0 OR p_freight_value<0 OR p_discount_value<0 OR p_discount_value>p_sale_value OR p_installments<1 OR p_sets_count<0 OR p_loose_pieces_count<0 OR p_status='CANCELLED' OR p_expected_revision IS NULL THEN RAISE EXCEPTION 'sales_validation' USING ERRCODE='22023';END IF;
 v_request:=jsonb_build_object('sale_id',p_sale_id,'consultant_profile_id',p_consultant_profile_id,'pv_number',btrim(p_pv_number),'sale_value',p_sale_value,'freight_value',p_freight_value,'discount_value',p_discount_value,'payment_method_id',p_payment_method_id,'installments',p_installments,'sets_count',p_sets_count,'loose_pieces_count',p_loose_pieces_count,'invoice_number',NULLIF(btrim(p_invoice_number),''),'status',p_status,'sold_at',p_sold_at,'expected_revision',p_expected_revision);
 PERFORM pg_advisory_xact_lock(hashtextextended(v_tenant::text||':sales:'||v_key,0));SELECT request,result INTO v_old_req,v_result FROM public.sales_mutation_requests WHERE tenant_id=v_tenant AND idempotency_key=v_key;IF v_result IS NOT NULL THEN IF v_old_req IS DISTINCT FROM v_request THEN RAISE EXCEPTION 'sales_idempotency_mismatch' USING ERRCODE='22023';END IF;RETURN v_result;END IF;
 IF NOT EXISTS(SELECT 1 FROM public.sales_memberships sm WHERE sm.tenant_id=v_tenant AND sm.profile_id=p_consultant_profile_id AND sm.role='CONSULTANT' AND sm.is_active) THEN RAISE EXCEPTION 'sales_ineligible_consultant' USING ERRCODE='23514';END IF;
 SELECT sp.id INTO v_period FROM public.sales_periods sp LEFT JOIN public.sales_config sc ON sc.tenant_id=sp.tenant_id WHERE sp.tenant_id=v_tenant AND sp.status='OPEN' AND (p_sold_at AT TIME ZONE COALESCE(sc.timezone,'America/Sao_Paulo'))::date BETWEEN sp.starts_on AND sp.ends_on ORDER BY sp.starts_on DESC LIMIT 1;IF v_period IS NULL THEN RAISE EXCEPTION 'sales_closed_period_or_not_found' USING ERRCODE='25006';END IF;
 IF p_payment_method_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.sales_payment_methods pm WHERE pm.tenant_id=v_tenant AND pm.id=p_payment_method_id AND pm.is_active) THEN RAISE EXCEPTION 'sales_invalid_payment_method' USING ERRCODE='23503';END IF;SELECT COALESCE(sc.pieces_per_set,2)INTO v_pps FROM(SELECT 1)q LEFT JOIN public.sales_config sc ON sc.tenant_id=v_tenant;
 IF p_sale_id IS NULL THEN IF p_expected_revision<>0 THEN RAISE EXCEPTION 'sales_stale_revision' USING ERRCODE='40001';END IF;INSERT INTO public.sales(tenant_id,period_id,consultant_profile_id,pv_number,sale_value,freight_value,discount_value,payment_method_id,installments,sets_count,loose_pieces_count,pieces_total,invoice_number,status,sold_at,revision)VALUES(v_tenant,v_period,p_consultant_profile_id,btrim(p_pv_number),p_sale_value,p_freight_value,p_discount_value,p_payment_method_id,p_installments,p_sets_count,p_loose_pieces_count,p_sets_count*v_pps+p_loose_pieces_count,NULLIF(btrim(p_invoice_number),''),p_status,p_sold_at,1)RETURNING to_jsonb(sales.*)INTO v_after;ELSE SELECT to_jsonb(s)INTO v_before FROM public.sales s JOIN public.sales_periods sp ON sp.tenant_id=s.tenant_id AND sp.id=s.period_id WHERE s.tenant_id=v_tenant AND s.id=p_sale_id AND sp.status='OPEN' AND s.status<>'CANCELLED' FOR UPDATE OF s;IF v_before IS NULL THEN RAISE EXCEPTION 'sales_closed_period_or_not_found' USING ERRCODE='25006';END IF;IF(v_before->>'revision')::bigint<>p_expected_revision THEN RAISE EXCEPTION 'sales_stale_revision' USING ERRCODE='40001',DETAIL=v_before::text;END IF;UPDATE public.sales SET period_id=v_period,consultant_profile_id=p_consultant_profile_id,pv_number=btrim(p_pv_number),sale_value=p_sale_value,freight_value=p_freight_value,discount_value=p_discount_value,payment_method_id=p_payment_method_id,installments=p_installments,sets_count=p_sets_count,loose_pieces_count=p_loose_pieces_count,pieces_total=p_sets_count*v_pps+p_loose_pieces_count,invoice_number=NULLIF(btrim(p_invoice_number),''),status=p_status,sold_at=p_sold_at,revision=revision+1,updated_at=now()WHERE tenant_id=v_tenant AND id=p_sale_id RETURNING to_jsonb(sales.*)INTO v_after;END IF;
 INSERT INTO public.sales_audit_events(tenant_id,actor_id,action,entity_type,entity_id,details)VALUES(v_tenant,v_actor,CASE WHEN p_sale_id IS NULL THEN'SALE_CREATED'ELSE'SALE_UPDATED'END,'sale',(v_after->>'id')::uuid,jsonb_build_object('before',v_before,'after',v_after));v_result:=jsonb_build_object('sale',v_after-'tenant_id','revalidate',jsonb_build_array('dashboard','sales-list','sale-detail'));INSERT INTO public.sales_mutation_requests(tenant_id,idempotency_key,operation,request,result)VALUES(v_tenant,v_key,'UPSERT',v_request,v_result);RETURN v_result;
EXCEPTION WHEN unique_violation THEN RAISE EXCEPTION 'sales_duplicate_pv' USING ERRCODE='23505';END;$$;

CREATE OR REPLACE FUNCTION public.sales_admin_sale_detail_v1(p_sale_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE v_tenant uuid:=public.auth_tenant_id();v_sale jsonb;
BEGIN
 IF v_tenant IS NULL OR auth.uid() IS NULL OR NOT public.sales_is_admin() THEN RAISE EXCEPTION 'sales_admin_required' USING ERRCODE='42501';END IF;
 SELECT to_jsonb(x) INTO v_sale FROM(SELECT s.id,s.pv_number,s.sale_value,s.freight_value,s.discount_value,s.payment_method_id,s.installments,s.sets_count,s.loose_pieces_count,s.pieces_total,s.invoice_number,s.status,s.sold_at,s.revision,s.consultant_profile_id,p.full_name consultant_name,s.period_id,sp.status period_status,sp.starts_on,sp.ends_on,s.cancelled_at,s.cancellation_reason,CASE WHEN sp.status='OPEN' AND s.status<>'CANCELLED' THEN true ELSE false END can_edit,CASE WHEN sp.status='OPEN' AND s.status<>'CANCELLED' THEN true ELSE false END can_cancel FROM public.sales s JOIN public.profiles p ON p.tenant_id=s.tenant_id AND p.id=s.consultant_profile_id JOIN public.sales_periods sp ON sp.tenant_id=s.tenant_id AND sp.id=s.period_id WHERE s.tenant_id=v_tenant AND s.id=p_sale_id)x;
 IF v_sale IS NULL THEN RAISE EXCEPTION 'sales_not_found_or_out_of_scope' USING ERRCODE='P0002';END IF;RETURN v_sale;
END;$$;

CREATE OR REPLACE FUNCTION public.sales_admin_cancel_sale_v2(p_sale_id uuid,p_expected_revision bigint,p_reason text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE v_tenant uuid:=public.auth_tenant_id();v_actor uuid:=auth.uid();v_key text:=btrim(COALESCE(p_idempotency_key,''));v_reason text:=btrim(COALESCE(p_reason,''));v_request jsonb;v_old_req jsonb;v_result jsonb;v_before jsonb;v_after jsonb;
BEGIN
 IF v_tenant IS NULL OR v_actor IS NULL OR NOT public.sales_is_admin() THEN RAISE EXCEPTION 'sales_admin_required' USING ERRCODE='42501';END IF;IF length(v_key)NOT BETWEEN 1 AND 200 OR length(v_reason)NOT BETWEEN 3 AND 500 OR p_expected_revision IS NULL THEN RAISE EXCEPTION 'sales_cancellation_validation' USING ERRCODE='22023';END IF;
 v_request:=jsonb_build_object('sale_id',p_sale_id,'revision',p_expected_revision,'reason',v_reason);PERFORM pg_advisory_xact_lock(hashtextextended(v_tenant::text||':sales:'||v_key,0));SELECT request,result INTO v_old_req,v_result FROM public.sales_mutation_requests WHERE tenant_id=v_tenant AND idempotency_key=v_key;IF v_result IS NOT NULL THEN IF v_old_req IS DISTINCT FROM v_request THEN RAISE EXCEPTION 'sales_idempotency_mismatch' USING ERRCODE='22023';END IF;RETURN v_result||jsonb_build_object('event_already_existed',true);END IF;
 SELECT to_jsonb(s)INTO v_before FROM public.sales s JOIN public.sales_periods sp ON sp.tenant_id=s.tenant_id AND sp.id=s.period_id WHERE s.tenant_id=v_tenant AND s.id=p_sale_id AND sp.status='OPEN' FOR UPDATE OF s;IF v_before IS NULL THEN RAISE EXCEPTION 'sales_closed_period_or_not_found' USING ERRCODE='25006';END IF;IF v_before->>'status'='CANCELLED' THEN IF v_before->>'cancellation_reason'<>v_reason THEN RAISE EXCEPTION 'sales_cancellation_conflict' USING ERRCODE='23514';END IF;v_result:=jsonb_build_object('sale',v_before-'tenant_id','event_already_existed',true);INSERT INTO public.sales_mutation_requests(tenant_id,idempotency_key,operation,request,result)VALUES(v_tenant,v_key,'CANCEL',v_request,v_result);RETURN v_result;END IF;IF(v_before->>'revision')::bigint<>p_expected_revision THEN RAISE EXCEPTION 'sales_stale_revision' USING ERRCODE='40001',DETAIL=v_before::text;END IF;
 UPDATE public.sales SET status='CANCELLED',cancelled_at=now(),cancelled_by_id=v_actor,cancellation_reason=v_reason,revision=revision+1,updated_at=now()WHERE tenant_id=v_tenant AND id=p_sale_id RETURNING to_jsonb(sales.*)INTO v_after;INSERT INTO public.sales_audit_events(tenant_id,actor_id,action,entity_type,entity_id,details)VALUES(v_tenant,v_actor,'SALE_CANCELLED','sale',p_sale_id,jsonb_build_object('before',v_before,'after',v_after,'reason',v_reason));v_result:=jsonb_build_object('sale',v_after-'tenant_id','event_already_existed',false,'revalidate',jsonb_build_array('dashboard','sales-list','sale-detail'));INSERT INTO public.sales_mutation_requests(tenant_id,idempotency_key,operation,request,result)VALUES(v_tenant,v_key,'CANCEL',v_request,v_result);RETURN v_result;
END;$$;

REVOKE EXECUTE ON FUNCTION public.sales_admin_dashboard_v2(uuid,uuid),public.sales_admin_list_sales_v1(uuid,uuid,public."SalesSaleStatus",integer,integer,text,text),public.sales_admin_sale_detail_v1(uuid),public.sales_admin_upsert_sale_v2(uuid,uuid,text,numeric,numeric,numeric,uuid,integer,integer,integer,text,public."SalesSaleStatus",timestamptz,bigint,text),public.sales_admin_cancel_sale_v2(uuid,bigint,text,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.sales_admin_dashboard_v2(uuid,uuid),public.sales_admin_list_sales_v1(uuid,uuid,public."SalesSaleStatus",integer,integer,text,text),public.sales_admin_sale_detail_v1(uuid),public.sales_admin_upsert_sale_v2(uuid,uuid,text,numeric,numeric,numeric,uuid,integer,integer,integer,text,public."SalesSaleStatus",timestamptz,bigint,text),public.sales_admin_cancel_sale_v2(uuid,bigint,text,text) TO authenticated;
COMMIT;
